-- Reviewed metadata only. No business evidence import or crawler activation.
begin;
select set_config('request.jwt.claims',json_build_object('sub',(select user_id from public.weig_kashrut_managers order by created_at limit 1),'role','authenticated')::text,true);
set local role authenticated;
update public.weig_kashrut_agencies set official_url='https://cor.ca/',base_country='CA',status='verified',notes='2026-10-06: זהות COR אומתה באתר הרשמי cor.ca: Kashruth Council of Canada, כתובת בטורונטו. פורסמו ערוצי בתי עסק, מוצרים, תעודות והתראות. אימות זהות בלבד; תנאי איסוף טרם נבדקו.' where code='cor';
update public.weig_kashrut_agencies set official_url='https://mk.ca/',base_country='CA',status='verified',aliases=array['MK Kosher','Montreal Kosher'],notes='2026-10-06: זהות MK אומתה באתר הרשמי mk.ca. האתר מפרסם ערוצי הסמכה, בתי עסק במונטריאול, חיפוש מוצרים והתראות. אימות זהות בלבד; לא נקבע כיסוי עולמי מלא או היתר איסוף.' where code='mk';
update public.weig_kashrut_agencies set official_url='https://kosher.org.au/',base_country='AU',status='verified',notes='2026-10-06: זהות Kosher Australia Pty Ltd אומתה באתר הרשמי kosher.org.au, עם כתובת בקולפילד, ויקטוריה. חיפוש המוצרים מפנה לכניסה. תנאי השימוש אוסרים איסוף אוטומטי ומגבילים שימוש מסחרי; נדרש אישור מפורש לחיבור.' where code='kosher_australia';
update public.weig_kashrut_review_tasks r set status='resolved',decision='2026-10-06: זהות הגוף אומתה לפי האתר הרשמי המתועד ברשומת הגוף. אימות אינו אישור תעודת עסק ואינו היתר איסוף אוטומטי.' from public.weig_kashrut_agencies a where r.agency_id=a.id and a.code in ('cor','mk','kosher_australia') and r.status in ('open','in_review');
update public.weig_kashrut_agencies set status='needs_review',notes='2026-10-06: בדיקת www.badatz.biz הציגה תוכן כשרות לצד כותרת הכוללת תוכן לא קשור על שעונים. זו חריגה המחייבת אימות שלמות ואותנטיות הערוץ; לא נקבע שהגוף או כשרותו אינם אמינים. האתר אינו מסומן כערוץ רשמי מאומת.' where code='beit_yosef';
update public.weig_kashrut_review_tasks r set reason='בדיקת https://www.badatz.biz/ ב-2026-10-06 הציגה כותרת עם תוכן זר. יש לוודא ערוץ רשמי תקין ומעודכן לפני אימות או חיבור.' from public.weig_kashrut_agencies a where r.agency_id=a.id and a.code='beit_yosef' and r.status in ('open','in_review');
update public.weig_kashrut_agencies set notes='2026-10-06: ניסיון לקרוא https://sheerit-israel.co.il/ לא החזיר תוכן שמאפשר אימות. נדרש ערוץ רשמי קריא או ראיה נוספת. אין להסיק מכך שאין גוף פעיל.' where code='sheerit';
update public.weig_kashrut_review_tasks r set reason='יש להשלים אימות מערוץ רשמי קריא; https://sheerit-israel.co.il/ לא החזיר תוכן שניתן לאמת בבדיקה זו.' from public.weig_kashrut_agencies a where r.agency_id=a.id and a.code='sheerit' and r.status in ('open','in_review');
update public.weig_kashrut_agencies set notes='2026-10-06: אותר https://yokneam.md.gov.il/home/ הנושא את השם מועצה דתית יקנעם. הרשומה הקיימת נקראת רבנות יקנעם. יש לברר זהות ותפקידים לפני איחוד, שינוי שם או רישום קשר; לא הוסק ששני השמות הם אותה ישות.' where code='yokneam_council';
update public.weig_kashrut_review_tasks r set reason='אותר ערוץ מועצה דתית יקנעם https://yokneam.md.gov.il/home/. נדרש לברר האם הרשומה מתארת מועצה או רבנות, ולהפריד בעל מקור מן הגוף המכשיר לפני אימות.' from public.weig_kashrut_agencies a where r.agency_id=a.id and a.code='yokneam_council' and r.status in ('open','in_review');
update public.weig_kashrut_registry_sources set content_kind='establishments',refresh_frequency='manual' where code in ('beit_shemesh_council','petah_tikva_council','netanya_council','yokneam_government','ou_kosher');
insert into public.weig_kashrut_registry_sources(code,name_he,agency_id,owner_agency_id,publisher,url,format,status,connection_state,coverage,content_kind,notes)
select 'cor_dining','COR — מדריך בתי עסק בטורונטו',id,id,'COR','https://cor.ca/consumers/kosher-dining-in-toronto/','html','verified','planned','טורונטו; לפי המדריך הרשמי','establishments','2026-10-06: קישור למדריך בתי עסק מהאתר הרשמי. שלמות, מזהים, תנאי גישה ותדירות טרם נבדקו; לא נאספו עסקים.' from public.weig_kashrut_agencies where code='cor' on conflict(code) do nothing;
insert into public.weig_kashrut_registry_sources(code,name_he,agency_id,owner_agency_id,publisher,url,format,status,connection_state,coverage,content_kind,notes)
select 'mk_dining','MK — מדריך בתי עסק במונטריאול',id,id,'MK','https://mk.ca/montreal/','html','verified','planned','מונטריאול; לפי המדריך הרשמי','establishments','2026-10-06: קישור רשמי למדריך בתי עסק; רשומות כוללות גם תחומים מוגבלים כגון דלפק. שלמות, מזהים ותנאי גישה טרם נבדקו; לא נאספו עסקים.' from public.weig_kashrut_agencies where code='mk' on conflict(code) do nothing;
insert into public.weig_kashrut_registry_sources(code,name_he,agency_id,owner_agency_id,publisher,url,format,status,connection_state,coverage,content_kind,access_status,terms_url,access_notes,notes)
select 'kosher_australia_products','Kosher Australia — חיפוש מוצרים',id,id,'Kosher Australia Pty Ltd','https://kosher.org.au/search','html','verified','blocked','חיפוש מוצרים; נדרשת כניסה; כיסוי טרם הוגדר','products','prohibited','https://kosher.org.au/pages/201903060723-Terms-of-Use','2026-10-06: תנאי Your Use of the Site אוסרים page-scrape, robot ואיסוף אוטומטי. שימוש מסחרי בתוכן דורש אישור מראש. אין היתר לחיבור.','2026-10-06: ערוץ המוצרים מקושר מהאתר הרשמי ומפנה לכניסה. לא בוצעה כניסה או איסוף. ניתן לבחון חיבור רק לאחר אישור מפורש מתועד.' from public.weig_kashrut_agencies where code='kosher_australia' on conflict(code) do nothing;
reset role;
commit;
select json_build_object('agencies_verified',(select count(*) from public.weig_kashrut_agencies where status='verified'),'sources',(select count(*) from public.weig_kashrut_registry_sources),'open_reviews',(select count(*) from public.weig_kashrut_review_tasks where status in ('open','in_review')),'active_connections',(select count(*) from public.weig_kashrut_registry_sources where connection_state='active')) as result;
