"use client";
import {useState} from "react";
import {MapPinned, Wallet, PhoneCall, Sparkles, Settings, Menu, X, Info, Bookmark, Languages, ChevronLeft, ChevronRight} from "lucide-react";
import Link from "next/link";
import {usePathname} from "next/navigation";
import type {Dictionary,Locale} from "@/i18n/dictionaries";
import {localizePath} from "@/i18n/routing";
import {Logo} from "./logo";
export const destinations=["places","expenses","calls","ai"] as const;
const glyphs={places:MapPinned,expenses:Wallet,calls:PhoneCall,ai:Sparkles};
export function AppShell({children,locale,dictionary}:{children:React.ReactNode;locale:Locale;dictionary:Dictionary}){
 const [open,setOpen]=useState(false),[section,setSection]=useState<"main"|"settings"|"about">("main");const path=usePathname()??"";const he=locale==="he";const destinationPath=path.replace(/^\/(he|en)/,"")||"/places";
 return <div className="app-shell"><header className="topbar"><Logo/><button className="icon-button" aria-label={dictionary.common.menu} aria-expanded={open} onClick={()=>{setSection("main");setOpen(true)}}><Menu size={23}/></button></header>
 {open&&<><button className="scrim" aria-label={dictionary.common.close} onClick={()=>setOpen(false)}/><aside className="drawer" aria-label={dictionary.common.menu}><div className="drawer-head"><button className="close-button" onClick={()=>setOpen(false)} aria-label={dictionary.common.close}><X size={23}/></button><Logo/></div>
 {section==="main"?<><div className="user-card"><div className="avatar">W</div><div><small>{dictionary.menu.signedAs}</small><strong>{dictionary.menu.guest}</strong></div></div><div className="drawer-section-label">{he?"עוד ב־WEIG":"More in WEIG"}</div><Link className="menu-row" href={localizePath(locale,"/places")+"?saved=1"} onClick={()=>setOpen(false)}><Bookmark size={19}/><span>{he?"מקומות שמורים":"Saved places"}</span>{he?<ChevronLeft size={17}/>:<ChevronRight size={17}/>}</Link><button className="menu-row" onClick={()=>setSection("settings")}><Settings size={19}/><span>{dictionary.nav.settings}</span>{he?<ChevronLeft size={17}/>:<ChevronRight size={17}/>}</button><button className="menu-row" onClick={()=>setSection("about")}><Info size={19}/><span>{he?"על WEIG":"About WEIG"}</span>{he?<ChevronLeft size={17}/>:<ChevronRight size={17}/>}</button><div className="drawer-spacer"/><div className="drawer-footnote">{dictionary.common.demo}</div></>:<><button className="drawer-back" onClick={()=>setSection("main")}>{he?<ChevronRight size={18}/>:<ChevronLeft size={18}/>} {dictionary.common.back}</button>{section==="settings"?<><h2>{dictionary.nav.settings}</h2><p className="drawer-description">{he?"בחרו את שפת התצוגה.":"Choose your display language."}</p><div className="drawer-section-label"><Languages size={17}/>{he?"שפה":"Language"}</div><Link className={`drawer-language ${he?"selected":""}`} href={localizePath("he",destinationPath)} onClick={()=>setOpen(false)}><span>עברית</span><span>HE</span></Link><Link className={`drawer-language ${he?"":"selected"}`} href={localizePath("en",destinationPath)} onClick={()=>setOpen(false)}><span>English</span><span>EN</span></Link></>:<><h2>{he?"על WEIG":"About WEIG"}</h2><p className="drawer-description">{he?"מקום אחד לגלות יעדים, לסדר הוצאות, להתקשר ולתכנן בדרך שלך.":"A place to discover, manage trip expenses, call and plan your way."}</p><div className="drawer-about-note">{he?"המקומות מוצגים להמחשה. חיפוש חי, שיחות ועוזר AI יפעלו לאחר חיבור השירותים.":"Places are a preview. Live search, calls and AI will work once their services are connected."}</div></>}</>}
 </aside></>}
 <main className="app-content">{children}</main><nav className="bottom-nav" aria-label={dictionary.common.primaryNav}><ul>{destinations.map(item=>{const active=path.includes(`/${item}`);const Icon=glyphs[item];return <li key={item}><Link aria-current={active?"page":undefined} href={localizePath(locale,`/${item}`)}><span className="nav-glyph"><Icon size={21} strokeWidth={active?2.3:1.8}/></span><span>{dictionary.nav[item]}</span></Link></li>})}</ul></nav></div>
}
