"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
import {ArrowLeft,ArrowRight,Info,Mail,ShieldCheck} from "lucide-react";
import type {Dictionary,Locale} from "@/i18n/dictionaries";
import {Logo,LogoMark} from "./layout/logo";

export function AuthExperience({t,locale}:{t:Dictionary;locale:Locale}){
 const [step,setStep]=useState<"email"|"code">("email");
 const [email,setEmail]=useState("");
 const router=useRouter();const he=locale==="he";
 function next(e:FormEvent){e.preventDefault();setStep("code")}
 function enterDemo(){router.push(`/${locale}/places`)}
 return <main className="auth-experience"><section className="auth-visual"><img src="/images/budapest-city.jpg" alt={he?"מבט על בודפשט והדנובה":"Budapest and the Danube"}/><span className="auth-visual-shade"/><div className="auth-visual-brand"><Logo/></div><div className="auth-visual-copy"><span>{he?"הדרך שלך מתחילה כאן":"YOUR WAY STARTS HERE"}</span><h1>{he?"לגלות עולם.\nלהרגיש בבית.":"Discover more.\nFeel at home."}</h1><p>{he?"מקומות, הוצאות, שיחה ועזרה בדרך — במקום אחד.":"Places, expenses, calls and help along the way — together."}</p></div><small>Photo: Krisztian Tabori / Unsplash</small></section><section className="auth-entry"><div className="auth-entry-inner"><div className="auth-entry-top"><LogoMark className="auth-entry-mark"/><span>{he?"ברוכים הבאים ל־WEIG":"Welcome to WEIG"}</span></div><h2>{step==="email"?t.auth.title:t.auth.codeTitle}</h2><p className="auth-entry-subtitle">{step==="email"?(he?"בחרו איך להתחיל את הדרך שלכם.":"Choose how to start your journey."):`${t.auth.codeBody} ${email}`}</p>{step==="email"?<><button className="auth-google" type="button" onClick={()=>alert(t.auth.missing)}><span className="auth-google-g">G</span>{t.auth.google}</button><div className="auth-divider"><span/>{t.auth.or}<span/></div><form onSubmit={next} className="auth-email-form"><label htmlFor="auth-email">{t.auth.email}</label><div className="auth-email-field"><Mail size={19}/><input id="auth-email" required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder={t.auth.emailPlaceholder}/></div><button className="auth-submit" type="submit">{t.auth.send}{he?<ArrowLeft size={19}/>:<ArrowRight size={19}/>}</button></form><button className="auth-demo" type="button" onClick={enterDemo}>{t.auth.demoEnter}{he?<ArrowLeft size={18}/>:<ArrowRight size={18}/>}</button></>:<form className="auth-email-form" onSubmit={e=>{e.preventDefault();alert(t.auth.missing)}}><label htmlFor="auth-code">{t.auth.code}</label><input id="auth-code" className="auth-code-input" required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} placeholder="••••••"/><button className="auth-submit" type="submit">{t.auth.verify}</button><button type="button" className="auth-change" onClick={()=>setStep("email")}>{t.auth.change}</button></form>}<div className="auth-demo-note"><Info size={16}/><span>{t.auth.missing}</span></div><div className="auth-trust"><ShieldCheck size={16}/>{he?"הפרטים שלך שייכים לך.":"Your details stay yours."}</div></div></section></main>
}
