"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {fields,labels,type Entity,type RecordRow} from "@/modules/kashrut-admin/registry";
import styles from "./kashrut-admin.module.css";
type Data=Record<Entity,RecordRow[]>;
type Snapshot={data:Data;audit:{id:number;table_name:string;operation:string;created_at:string}[];truncated:boolean};
const titles:Record<Entity,string>={agencies:"גופים ורשויות",classifications:"מילון סיווגים",sources:"מקורות מידע",reviews:"תור בדיקה"};
const tableNames:Record<string,string>={weig_kashrut_agencies:"גוף",weig_kashrut_classifications:"סיווג",weig_kashrut_registry_sources:"מקור",weig_kashrut_review_tasks:"בדיקה"};
export function KashrutAdmin({locale}:{locale:string}){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[gate,setGate]=useState(""),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const [tab,setTab]=useState<Entity|"audit">("agencies"),[query,setQuery]=useState(""),[filter,setFilter]=useState("");
 const [editing,setEditing]=useState<{entity:Entity;row:RecordRow|null;values:Record<string,unknown>}|null>(null),[busy,setBusy]=useState(false);
 async function load(){
  setLoading(true);setError("");
  try{const r=await fetch("/api/kashrut/admin",{cache:"no-store"});const d=await r.json();if(r.status===401||r.status===403){setSnapshot(null);setGate(d.error);return}if(!r.ok)throw Error(d.error||"טעינת המאגר נכשלה");setSnapshot(d);setGate("")}catch(e){setError(e instanceof Error?e.message:"טעינת המאגר נכשלה")}finally{setLoading(false)}
 }
 useEffect(()=>{void load()},[]);
 function edit(entity:Entity,row:RecordRow|null){
  const values:Record<string,unknown>={};for(const f of fields[entity])values[f.key]=row?.[f.key]??(f.type==="array"?[]:f.type==="boolean"?true:f.options?.[0]??"");
  if(entity==="sources"&&!row){values.status="candidate";values.connection_state="planned";values.completeness="unknown"}
  setEditing({entity,row,values});setError("");setSuccess("");
 }
 async function save(e:React.FormEvent){
  e.preventDefault();if(!editing)return;setBusy(true);setError("");setSuccess("");
  try{const r=await fetch("/api/kashrut/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({entity:editing.entity,id:editing.row?.id,version:editing.row?.version,values:editing.values})});const d=await r.json();if(!r.ok)throw Error(d.error||"השמירה נכשלה");setEditing(null);setSuccess("השינוי נשמר במאגר ובהיסטוריית השינויים.");await load()}catch(e){setError(e instanceof Error?e.message:"השמירה נכשלה")}finally{setBusy(false)}
 }
 const display=(value:unknown)=>labels[String(value)]??String(value??"");
 const name=(entity:Entity,id:unknown)=>String(snapshot?.data[entity].find(r=>r.id===id)?.name_he??"פריט מקושר");
 const rows=tab!=="audit"?(snapshot?.data[tab]??[]).filter(r=>(!query||[r.name_he,r.name_en,r.code,r.title,r.notes,r.coverage,...(Array.isArray(r.aliases)?r.aliases:[])].join(" ").toLowerCase().includes(query.toLowerCase()))&&(!filter||r.status===filter||r.category===filter)):[];
 return <div className={styles.page} dir="rtl">
  <header className={styles.header}><div><span className={styles.eyebrow}>WEIG · מערכת ניהול</span><h1>מקורות וסיווגי כשרות</h1><p>מאגר גופים, סיווגים ומקורות רשמיים. אימות זהות גוף או מקור אינו אימות תעודת כשרות של עסק.</p></div><button className={styles.button} onClick={()=>void load()} disabled={loading||busy}>רענון</button></header>
  {loading&&!snapshot&&<p role="status">טוענים את מאגר הניהול…</p>}
  {gate&&<section className={styles.gate}><h2>{gate==="LOGIN_REQUIRED"?"כניסה למערכת הניהול":"נדרשת הרשאת ניהול"}</h2><p>{gate==="LOGIN_REQUIRED"?"התחברו לחשבון שהוגדר כמנהל כשרות כדי לפתוח את המאגר.":"החשבון מחובר, אך טרם הוגדר כמנהל כשרות. הרשאות ניתנות על ידי בעל הפרויקט לחשבון מסוים."}</p><Link className={`${styles.button} ${styles.primary}`} href={`/${locale}/auth`}>כניסה לחשבון</Link></section>}
  {error&&<p className={styles.error} role="alert">{error}</p>}{success&&<p className={styles.success} role="status">{success}</p>}
  {snapshot&&<>
   <div className={styles.stats}>{(Object.keys(titles) as Entity[]).map(key=><div className={styles.stat} key={key}><strong>{key==="reviews"?snapshot.data[key].filter(r=>r.status==="open"||r.status==="in_review").length:snapshot.data[key].length}</strong><span>{key==="reviews"?"בדיקות פתוחות":titles[key]}</span></div>)}</div>
   <p className={styles.note}>שלב הקמת התשתית. איסוף לפי אזורים וסריקות מתוזמנות יוגדרו לאחר השלמת מערכת המקורות. המקורות שיובאו בעבר מסומנים כיבוא ידני.</p>
   {snapshot.truncated&&<p className={styles.note}>מוצגות עד 1,000 רשומות בכל מאגר. יש לצמצם את המאגר או להוסיף עימוד לפני ניהול כמויות גדולות יותר.</p>}
   <nav className={styles.tabs} aria-label="מאגרי ניהול">{(Object.keys(titles) as Entity[]).map(key=><button className={styles.tab} key={key} aria-pressed={tab===key} onClick={()=>{setTab(key);setFilter("");setQuery("");setEditing(null)}}>{titles[key]}</button>)}<button className={styles.tab} aria-pressed={tab==="audit"} onClick={()=>{setTab("audit");setEditing(null)}}>היסטוריית שינויים</button></nav>
   {tab!=="audit"&&<div className={styles.toolbar}><input aria-label="חיפוש במאגר" placeholder="חיפוש לפי שם, מזהה או פרטים…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="סינון רשומות" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">כל הרשומות</option>{(tab==="classifications"?fields.classifications.find(f=>f.key==="category")!.options:fields[tab].find(f=>f.key==="status")!.options)?.map(o=><option key={o} value={o}>{display(o)}</option>)}</select><button className={`${styles.button} ${styles.primary}`} onClick={()=>edit(tab,null)}>הוספת {tab==="agencies"?"גוף":tab==="sources"?"מקור":tab==="reviews"?"בדיקה":"סיווג"}</button></div>}
   {editing&&<section className={styles.panel}><h2>{editing.row?"עריכת רשומה":"רשומה חדשה"} · {titles[editing.entity]}</h2><form onSubmit={save}><div className={styles.form}>{fields[editing.entity].filter(f=>editing.entity!=="reviews"||!["agency_id","source_id","classification_id"].includes(f.key)||f.key===`${editing.values.subject_type}_id`).map(f=><label className={`${styles.field} ${f.type==="textarea"?styles.wide:""}`} key={f.key}><span>{f.label}{f.required?" *":""}</span>{f.type==="boolean"?<input type="checkbox" checked={editing.values[f.key]===true} onChange={e=>setEditing({...editing,values:{...editing.values,[f.key]:e.target.checked}})}/>:f.options||f.reference?<select className={styles.input} required={f.required||f.reference&&editing.entity==="reviews"} value={String(editing.values[f.key]??"")} onChange={e=>setEditing({...editing,values:{...editing.values,[f.key]:e.target.value}})}>{f.reference?<><option value="">בחרו פריט</option>{snapshot.data[f.reference].map(r=><option key={r.id} value={r.id}>{String(r.name_he??r.title)}</option>)}</>:f.options!.map(o=><option key={o} value={o}>{display(o)}</option>)}</select>:f.type==="textarea"?<textarea className={styles.input} maxLength={4000} value={String(editing.values[f.key]??"")} onChange={e=>setEditing({...editing,values:{...editing.values,[f.key]:e.target.value}})}/>:<input className={styles.input} required={f.required} readOnly={f.key==="code"&&!!editing.row} dir={f.key==="url"||f.key==="official_url"||f.key==="code"?"ltr":undefined} value={Array.isArray(editing.values[f.key])?(editing.values[f.key] as string[]).join(", "):String(editing.values[f.key]??"")} onChange={e=>setEditing({...editing,values:{...editing.values,[f.key]:f.type==="array"?e.target.value.split(",").map(s=>s.trim()):e.target.value}})}/>}</label>)}</div><p className={styles.note}>יש לתעד ראיות לפני סימון גוף או מקור כמאומת. סיום בדיקה מחייב החלטה מנומקת ואינו משנה אוטומטית את מצב הפריט.</p><div className={styles.actions}><button type="button" className={styles.button} disabled={busy} onClick={()=>setEditing(null)}>ביטול</button><button className={`${styles.button} ${styles.primary}`} disabled={busy}>{busy?"שומרים…":"שמירת רשומה"}</button></div></form></section>}
   {tab==="audit"?<section className={styles.panel}><h2>50 השינויים האחרונים</h2>{snapshot.audit.map(r=><div className={styles.audit} key={r.id}>{new Date(r.created_at).toLocaleString("he-IL",{timeZone:"Asia/Jerusalem"})} · {tableNames[r.table_name]??r.table_name} · {r.operation==="INSERT"?"נוצרה רשומה":"הרשומה עודכנה"}</div>)}</section>:<section className={styles.rows} aria-label={titles[tab]}>{!rows.length&&<div className={styles.empty}>לא נמצאו רשומות מתאימות.</div>}{rows.map(r=><article className={styles.card} key={r.id}><div><h3>{String(r.name_he??r.title)}</h3><div className={styles.badges}>{[r.kind,r.category,r.status,r.connection_state,r.active===false?"inactive":null].filter(Boolean).map((v,i)=><span key={i} className={`${styles.badge} ${v==="verified"?styles.verified:v==="candidate"||v==="open"?styles.pending:""}`}>{display(v)}</span>)}</div>{tab==="sources"&&<p>גוף: {name("agencies",r.agency_id)} · מפרסם: {String(r.publisher||"לא פורסם")} · {String(r.coverage||"כיסוי לא פורסם")}</p>}{tab==="agencies"&&<p>{Array.isArray(r.countries)?r.countries.join(" · "):""}{Array.isArray(r.aliases)&&r.aliases.length?` · ${r.aliases.join(" / ")}`:""}</p>}{tab==="reviews"&&<p>{name(r.subject_type==="agency"?"agencies":r.subject_type==="source"?"sources":"classifications",r.agency_id??r.source_id??r.classification_id)} · {String(r.reason)}</p>}{r.description? <p>{String(r.description)}</p>:null}{r.notes?<p>{String(r.notes)}</p>:null}{r.decision?<p>החלטה: {String(r.decision)}</p>:null}{Boolean(r.official_url||r.url)&&<a href={String(r.official_url??r.url)} target="_blank" rel="noopener noreferrer">למקור הרשום ↗</a>}<small>{r.code?String(r.code):""} · עודכן {new Date(String(r.updated_at)).toLocaleDateString("he-IL",{timeZone:"Asia/Jerusalem"})}</small></div><button className={styles.button} onClick={()=>edit(tab,r)}>עריכה</button></article>)}</section>}
  </>}
 </div>;
}
