"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Bookmark, ChevronDown, ChevronLeft, ChevronRight, Compass, Heart, Images, List, Map as MapIcon, MapPin, Navigation, Search, SlidersHorizontal, Sparkles, X, Clock3, UtensilsCrossed } from "lucide-react";
import type { Dictionary } from "@/i18n/dictionaries";
import { useSearchParams } from "next/navigation";

type Place = { id:string; image:string; he:string; en:string; kindHe:string; kindEn:string; areaHe:string; areaEn:string; descriptionHe:string; descriptionEn:string; maps:string; credit:string; type:"heritage"|"views" };
const places:Place[]=[
 {id:"bastion",image:"/images/fishermans-bastion.jpg",he:"מצודת הדייגים",en:"Fisherman's Bastion",kindHe:"תצפית · אדריכלות",kindEn:"Views · Architecture",areaHe:"בודה · בודפשט",areaEn:"Buda · Budapest",descriptionHe:"מרפסות אבן ותצפית אל העיר. מקום טוב להתחיל בו יום של הליכה וגלות.",descriptionEn:"Stone terraces with sweeping city views. A beautiful starting point for a day on foot.",maps:"Fisherman's Bastion Budapest",credit:"Attila Pál / Unsplash",type:"views"},
 {id:"synagogue",image:"/images/dohany-synagogue.jpg",he:"בית הכנסת ברחוב דוהאני",en:"Dohány Street Synagogue",kindHe:"מורשת · היסטוריה",kindEn:"Heritage · History",areaHe:"הרובע היהודי · בודפשט",areaEn:"Jewish Quarter · Budapest",descriptionHe:"נקודת ציון ברובע היהודי של בודפשט, עם סיפור ועיצוב יוצאי דופן.",descriptionEn:"A landmark in Budapest's Jewish Quarter with remarkable history and architecture.",maps:"Dohany Street Synagogue Budapest",credit:"Linda Gerbec / Unsplash",type:"heritage"},
 {id:"river",image:"/images/budapest-parliament.jpg",he:"טיילת הדנובה",en:"Danube Promenade",kindHe:"הליכה · נוף עירוני",kindEn:"Walk · City view",areaHe:"מרכז בודפשט",areaEn:"Central Budapest",descriptionHe:"הליכה לצד הנהר מול בניין הפרלמנט וקו הרקיע של העיר.",descriptionEn:"A riverside walk with views of Parliament and the city skyline.",maps:"Danube Promenade Budapest",credit:"Himmel S / Unsplash",type:"views"},
 {id:"city",image:"/images/budapest-city.jpg",he:"גשר השלשלאות",en:"Chain Bridge",kindHe:"סמל העיר · הליכה",kindEn:"Landmark · Walk",areaHe:"מרכז בודפשט",areaEn:"Central Budapest",descriptionHe:"הגשר המחבר בין בודה לפשט ומציע מבט פתוח על העיר והנהר.",descriptionEn:"The bridge between Buda and Pest, opening up views across the city and river.",maps:"Szechenyi Chain Bridge Budapest",credit:"Krisztian Tabori / Unsplash",type:"views"}
];
export function PlacesExperience({t}:{t:Dictionary}) {
 const searchParams=useSearchParams();const he=t.places.title==="לאן תרצו להגיע?";const label=(h:string,e:string)=>he?h:e;const arrow=he?<ArrowLeft size={18}/>:<ArrowRight size={18}/>;
 const [query,setQuery]=useState(""),[category,setCategory]=useState<"all"|"heritage"|"views">("all"),[selected,setSelected]=useState<Place|null>(null),[view,setView]=useState<"feed"|"list"|"map">("feed"),[saved,setSaved]=useState<string[]>([]),[locationNote,setLocationNote]=useState(false),[showSaved,setShowSaved]=useState(false);
 useEffect(()=>{setShowSaved(searchParams.get("saved")==="1")},[searchParams]);
 const visible=useMemo(()=>places.filter(p=>(category==="all"||p.type===category)&&(!showSaved||saved.includes(p.id))&&(!query.trim()||`${p.he} ${p.en} ${p.kindHe} ${p.kindEn} ${p.areaHe} ${p.areaEn}`.toLowerCase().includes(query.trim().toLowerCase()))),[category,query,saved,showSaved]);
 useEffect(()=>{try{const value=JSON.parse(localStorage.getItem("weig-saved-places")||"[]");if(Array.isArray(value))setSaved(value.filter((x):x is string=>typeof x==="string"))}catch{}},[]);
 const toggle=(id:string)=>setSaved(v=>{const next=v.includes(id)?v.filter(x=>x!==id):[...v,id];try{localStorage.setItem("weig-saved-places",JSON.stringify(next))}catch{}return next});const title=(p:Place)=>he?p.he:p.en;
 return <div className="discover-app">
  <div className="discover-topline"><div><span className="discover-eyebrow">{label("מגלים עם WEIG","WEIG DISCOVER")}</span><h1>{label("לגלות", "Discover")}</h1></div><button className="discover-city" onClick={()=>setLocationNote(v=>!v)}><MapPin size={16}/>{label("בודפשט", "Budapest")}<ChevronDown size={15}/></button></div>
  <div className="discover-search"><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label={t.places.search} placeholder={label("איזה מקום מתחשק לך לגלות?","What would you like to discover?")}/>{query&&<button aria-label={label("נקה חיפוש","Clear search")} onClick={()=>setQuery("")}><X size={18}/></button>}<button className="discover-search-filter" aria-label={label("הצג סינון","Show filters")} onClick={()=>setCategory(category==="all"?"heritage":"all")}><SlidersHorizontal size={19}/></button></div>
  {locationNote&&<p className="discover-context" role="status">{label("כעת מוצגות דוגמאות מבודפשט. בחירת יעד ומקומות בסביבה ייפתחו עם חיבור מאגר המקומות.","Budapest is the preview destination. Destination selection and nearby search need the places catalog.")}</p>}
  <div className="discover-chips" aria-label={t.places.categories}><button aria-pressed={category==="all"} onClick={()=>setCategory("all")}>{label("בשבילי","For you")}</button><button aria-pressed={category==="heritage"} onClick={()=>setCategory("heritage")}>{label("מורשת","Heritage")}</button><button aria-pressed={category==="views"} onClick={()=>setCategory("views")}>{label("נוף וטיול","Views & walks")}</button><button onClick={()=>{setQuery(label("כשר","kosher"));setCategory("all")}}>{label("אוכל כשר","Kosher food")}</button><button onClick={()=>{setQuery(label("מלון","hotel"));setCategory("all")}}>{label("לינה","Stays")}</button></div>
  <div className={view==="feed"?"discover-editorial feed-mode":"discover-editorial"}><div><span className="discover-overline"><span className="discover-pulse"/>{label("בודפשט, מקרוב", "BUDAPEST, UP CLOSE")}</span><h2>{query?label("תוצאות החיפוש", "Search results"):category==="heritage"?label("סיפורים בדרך", "Stories along the way"):category==="views"?label("לצאת לראות", "Step outside"):label("לאן היום?", "Where to today?")}</h2></div><div className="discover-view-actions"><div className="discover-mode-switch" aria-label={label("צורת תצוגה","View mode")}><button aria-label={label("פיד","Feed")} aria-pressed={view==="feed"} onClick={()=>setView("feed")}><Images size={17}/>{label("פיד","Feed")}</button><button aria-label={label("רשימה","List")} aria-pressed={view==="list"} onClick={()=>setView("list")}><List size={17}/>{label("רשימה","List")}</button><button aria-label={label("מפה","Map")} aria-pressed={view==="map"} onClick={()=>setView("map")}><MapIcon size={17}/>{label("מפה","Map")}</button></div><button className="discover-saved-toggle" aria-pressed={showSaved} onClick={()=>{setShowSaved(v=>!v);setView("feed")}}><Bookmark size={17}/>{label("שמורים", "Saved")}{saved.length>0&&<span>{saved.length}</span>}</button></div></div>
  {view==="map"?<div className="discover-map-empty"><MapIcon size={36}/><h3>{label("המפה עוד בדרך", "The map is on its way")}</h3><p>{label("כשמאגר המקומות יחובר, נציג כאן מיקומים ומסלולים אמיתיים.","Verified places and routes will appear here when the catalog is connected.")}</p><button onClick={()=>setView("feed")}>{label("חזרה למקומות", "Back to places")}</button></div>:visible.length?view==="feed"?<Feed places={visible} he={he} saved={saved} toggle={toggle} select={setSelected}/>:<ListView places={visible} he={he} saved={saved} toggle={toggle} select={setSelected}/>:<div className="discover-no-results"><Search size={28}/><h3>{showSaved?label("עוד לא שמרת מקומות","No saved places yet"):label("עוד אין כאן תוצאות", "No results here yet")}</h3><p>{showSaved?label("לחצו על הלב ליד מקום שמעניין אתכם כדי לשמור אותו כאן.","Tap the heart on a place to save it here."):label("החיפוש החי יפעל עם חיבור מאגר המקומות. בינתיים אפשר לעיין במקומות שבהדגמה.","Live search needs a connected places catalog. You can explore the preview places for now.")}</p><button onClick={()=>{setQuery("");setCategory("all");setShowSaved(false)}}>{label("להציג את המקומות", "Show preview places")}</button></div>}
  <p className="discover-disclaimer">{label("תצוגת מוצר לדוגמה. תמונות האתרים אמיתיות; שעות פעילות, מרחק וכשרות אינם מאומתים.","Product preview. Landmark photographs are real; hours, distance and kosher status are not verified.")}</p>
  {selected&&<div className="discover-detail-wrap"><button className="discover-detail-backdrop" onClick={()=>setSelected(null)} aria-label={t.common.close}/><article className="discover-detail" role="dialog" aria-modal="true" aria-label={title(selected)}><div className="discover-detail-photo"><img src={selected.image} alt={title(selected)}/><button onClick={()=>setSelected(null)} aria-label={t.common.close}><X size={21}/></button><span>{selected.credit}</span></div><div className="discover-detail-body"><span className="discover-eyebrow">{he?selected.kindHe:selected.kindEn}</span><h2>{title(selected)}</h2><p className="discover-detail-area"><MapPin size={16}/>{he?selected.areaHe:selected.areaEn}</p><p>{he?selected.descriptionHe:selected.descriptionEn}</p><div className="discover-facts"><span><Clock3 size={17}/>{label("שעות פתיחה טרם אומתו", "Hours not verified")}</span><span><UtensilsCrossed size={17}/>{label("כשרות טרם אומתה", "Kosher status not verified")}</span></div><div className="discover-detail-actions"><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(selected.maps)}`} target="_blank" rel="noopener noreferrer"><Navigation size={19}/>{label("לפתוח במפות", "Open in Maps")}</a><button aria-label={saved.includes(selected.id)?label("הסר משמורים","Remove saved"):label("שמירת מקום","Save place")} aria-pressed={saved.includes(selected.id)} onClick={()=>toggle(selected.id)}><Bookmark size={19} fill={saved.includes(selected.id)?"currentColor":"none"}/></button></div><small>{label("קישור לחיפוש המקום. יש לבדוק פרטים לפני ההגעה.","Opens a place search. Check details before visiting.")}</small></div></article></div>}
 </div>
}

function Feed({places:items,he,saved,toggle,select}:{places:Place[];he:boolean;saved:string[];toggle:(id:string)=>void;select:(place:Place)=>void}){
 const label=(h:string,e:string)=>he?h:e;
 return <div className="discover-feed"><p className="discover-feed-count">{items.length} {label("מקומות לגלות · גללו למקום הבא","places to discover · scroll for the next one")}</p><div className="discover-feed-list">{items.map((place,index)=><article className="discover-feed-card" key={place.id}>
  <img src={place.image} alt={he?place.he:place.en}/><div className="discover-feed-shade"/>
  <div className="discover-feed-top"><span><MapPin size={14}/>{he?place.areaHe:place.areaEn}</span><span dir="ltr">{String(index+1).padStart(2,"0")} / {String(items.length).padStart(2,"0")}</span></div>
  <div className="discover-feed-actions"><button aria-label={`${saved.includes(place.id)?label("הסר משמורים","Remove saved"):label("שמירה","Save")} ${he?place.he:place.en}`} aria-pressed={saved.includes(place.id)} onClick={()=>toggle(place.id)}><Heart size={22} fill={saved.includes(place.id)?"currentColor":"none"}/></button><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place.maps)}`} target="_blank" rel="noopener noreferrer" aria-label={`${label("מפות","Maps")} ${he?place.he:place.en}`}><Navigation size={21}/></a></div>
  <div className="discover-feed-caption"><span>{he?place.kindHe:place.kindEn}</span><h3>{he?place.he:place.en}</h3><p>{he?place.descriptionHe:place.descriptionEn}</p><button onClick={()=>select(place)}>{label("לגלות את המקום","Explore place")}{he?<ArrowLeft size={18}/>:<ArrowRight size={18}/>}</button></div>
  <small className="discover-feed-credit">{place.credit}</small>
 </article>)}</div></div>
}

function ListView({places:items,he,saved,toggle,select}:{places:Place[];he:boolean;saved:string[];toggle:(id:string)=>void;select:(place:Place)=>void}){
 const label=(h:string,e:string)=>he?h:e;
 return <section className="discover-results"><div className="discover-results-heading"><strong>{items.length} {label("מקומות בבודפשט","places in Budapest")}</strong><span>{label("מקומות לדוגמה","Preview places")}</span></div><div className="discover-results-list">{items.map(p=><article className="discover-result" key={p.id}><button className="discover-result-main" onClick={()=>select(p)}><img src={p.image} alt=""/><span className="discover-result-copy"><small>{he?p.kindHe:p.kindEn}</small><strong>{he?p.he:p.en}</strong><span><MapPin size={13}/>{he?p.areaHe:p.areaEn}</span></span>{he?<ChevronLeft size={17}/>:<ChevronRight size={17}/>}</button><button className="discover-result-save" aria-label={`${saved.includes(p.id)?label("הסר משמורים","Remove saved"):label("שמירה","Save")} ${he?p.he:p.en}`} aria-pressed={saved.includes(p.id)} onClick={()=>toggle(p.id)}><Bookmark size={18} fill={saved.includes(p.id)?"currentColor":"none"}/></button></article>)}</div></section>
}
